
package com.demo.webservice.client.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloService", targetNamespace = "http://server.webservice.demo.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getValue", targetNamespace = "http://server.webservice.demo.com/", className = "com.demo.webservice.client.ws.GetValue")
    @ResponseWrapper(localName = "getValueResponse", targetNamespace = "http://server.webservice.demo.com/", className = "com.demo.webservice.client.ws.GetValueResponse")
    @Action(input = "http://server.webservice.demo.com/HelloService/getValueRequest", output = "http://server.webservice.demo.com/HelloService/getValueResponse")
    public String getValue(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
